config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :things do
    resources :comments
    member do
      post :create_comment
      get :next_comments
    end
  end

  get  'sessions/sign_up_form'
  post 'sessions/sign_up'
  get  'sessions/sign_out'

  get  'sessions/sign_in_form'
  post 'sessions/sign_in'

  get  'sessions/wake_up_form/:id', controller: :sessions, action: :wake_up_form
  post 'sessions/wake_up/:id', controller: :sessions, action: :wake_up, as: :session_wake_up

  root 'things#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/authorship.rb
class Authorship < ApplicationRecord
  belongs_to :thing
  belongs_to :user
end

app/models/cache_version.rb
class CacheVersion < ApplicationRecord
  def self.for(name)
    where(name: name).first or create(name: name)
  end

  # called in AS::Cache#retrieve_cache_key
  def cache_key
    updated_at
  end

  def expire!
    update_attribute(:updated_at, (updated_at || Time.now) + 1.second)
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :thing
end

app/models/thing.rb
class Thing < ApplicationRecord
  serialize :image_meta_data

  has_many :authorships
  has_many :users, through: :authorships

  has_many :comments, dependent: :destroy

  scope :latest, -> { all.limit(9).order(id: :desc) }
end

app/models/user.rb
class User < ApplicationRecord
  serialize :auth_meta_data

  has_many :authorships, dependent: :destroy
  has_many :things, through: :authorships
  has_many :comments, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def tyrant
    Tyrant::Session.new request.env['warden']
  end
  helper_method :tyrant
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @thing = Thing.find(params[:thing_id]) # UI-specific logic!

    run Comment::Operation::Create
    # @form.prepopulate!
  end

  def create
    run Comment::Operation::Create do |ctx|
      flash[:notice] = "Created comment for \"#{ctx[:model].thing.name}\""

      return redirect_to thing_path(ctx[:model].thing)
    end

    @thing = Thing.find(params[:thing_id]) # UI-specific logic!
    render :new
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  # before_filter should be used when op not involved at all.
  before_action only: %i[sign_in_form sign_up_form] do
    redirect_to root_path if tyrant.signed_in?
  end

  def sign_up_form
    run Session::Operation::SignUp
  end

  def sign_up
    run Session::Operation::SignUp do |_result|
      flash[:notice] = 'Please log in now!'
      return redirect_to sessions_sign_in_form_path
    end

    flash.now[:alert] = @form.errors.messages
    render action: :sign_up_form
  end

  def sign_in_form
    run Session::Operation::SignIn
  end

  def sign_in
    run Session::Operation::SignIn do |result|
      flash[:notice] = 'Successfully signed in'
      tyrant.sign_in! result['contract.default'].user
      return redirect_to root_path
    end

    flash.now[:alert] = @form.errors.messages
    render action: :sign_in_form
  end

  def wake_up_form
    run Session::Operation::WakeUp::Form do
      return # continue rendering form is token is valid
    end

    flash[:alert] = result[:error_message]
    redirect_to root_path
  end

  def wake_up
    run Session::Operation::WakeUp do
      flash[:notice] = 'Password changed'
      return redirect_to sessions_sign_in_form_path
    end

    render :wake_up_form
  end

  def sign_out
    run Session::Operation::SignOut do
      tyrant.sign_out!
      redirect_to root_path
    end
  end
end

app/controllers/things_controller.rb
class ThingsController < ApplicationController
  def index; end

  def show
    thing_operation = run Thing::Operation::Update
    @thing = thing_operation[:model]

    run Comment::Operation::Create # overrides @model and @form
  end

  def create_comment
    thing_operation = run Thing::Operation::Update
    @thing = thing_operation[:model]

    run Comment::Operation::Create, params: params.merge(thing_id: params[:id]) do
      flash[:notice] = "Created comment for \"#{@thing.name}\""
      return redirect_to thing_path(@thing)
    end

    flash.now[:alert] = 'Error'
    render :show
  end

  def next_comments
    run Thing::Operation::Update

    render js: concept('/comment/cell/grid', @model, page: params[:page]).(:append)
  end

  def new
    run Thing::Operation::Create
    @form.prepopulate!
  end

  def create
    run Thing::Operation::Create do |result|
      flash[:notice] = 'Successfully created'
      return redirect_to thing_path(result[:model])
    end

    flash.now[:alert] = 'Error'
    render action: :new
  end

  def edit
    run Thing::Operation::Update
    @form.prepopulate!
    render action: :new
  end

  def update
    run Thing::Operation::Update do |result|
      flash[:notice] = 'Successfully updated'
      return redirect_to thing_path(result[:model])
    end

    flash.now[:alert] = 'Error'
    render action: :new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/new.html.haml
.header
  %h1
    - ##{@thing.name}

= @form.errors.messages if @form.errors.present?
= form_for [@thing, @form] do |f| # POST /things/1/comments/
  %h3 What do you think?

  = f.text_field :body, placeholder: 'Your comment'
  = f.collection_radio_buttons :weight, *@form.weights

  = f.fields_for :user do |ff|
    = ff.text_field :email, placeholder: 'Your Email'

  = f.button :submit, class: :expand

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  %div{:class => "alert-box round #{name.to_s == 'notice' ? 'success' : 'alert'}", "data-alert" => ""}
    = content_tag :div, msg
    %a.close{:href => "#"} &times;

app/views/layouts/_navigation.html.haml
%nav.top-bar{"data-topbar" => true}
  %ul.title-area
    %li.name
      = link_to 'Home', root_path
    %li.toggle-topbar.menu-icon
      %a{:href => "#"}
        Menu
  .top-bar-section
    %ul
      = render 'layouts/navigation_links'

app/views/layouts/_navigation_links.html.haml
%li
  = link_to "Start discussion!", new_thing_path

- if tyrant.signed_in?
  %li
    = link_to "Hi, #{tyrant.current_user.email}", '#' #user_path(tyrant.current_user)
  %li
    = link_to "Sign out", sessions_sign_out_path
- else
  %li
    = link_to "Sign in", sessions_sign_in_form_path
  %li
    = link_to "Sign up", sessions_sign_up_form_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GemgemTrbRails6</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />


    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track':'reload'%>
  </head>

  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role='main'>
      <%= render 'layouts/messages' %>
    </main>
    <%= yield %>
  </body>
</html>

app/views/things/index.html.haml
%h3 Index
.row
  = concept('thing/cell/grid')

= link_to 'New', new_thing_path

app/views/things/new.html.haml
%h3 New thing

-# = form_for Thing.last do |f|
-#   = f.text_field :name
-#   = f.submit
= @form.errors if @form.errors.present?
= form_for @form do |f|
  = f.text_field :name, placeholder: 'Name', readonly: @form.readonly?(:name)
  = f.text_area :description, placeholder: 'Description'
  = f.file_field :file
  %fieldset
    %legend Do you know any authors?
    = f.fields_for :users do |ff|
      .row
        = ff.text_field :email, readonly: ff.object.removeable?, 'data-test': 'email'

        - if ff.object.removeable?
          = ff.check_box :remove

  = f.button 'Submit', class: :expand

= @form.errors.messages

= link_to 'Index', things_path

app/views/things/show.html.haml
%h3
  Show

= concept('thing/cell/decorator', @thing).(:thumb)

%strong
  #{@thing.name}
  = link_to 'Edit', edit_thing_path(@thing)

%p
  #{@thing.description}

%fieldset
  %legend Users
  - @thing.users.each do |user|
    .row
      = user.email


= @form.errors.messages if @form.errors.present?
= form_for @form, url: create_comment_thing_path(@thing) do |f|
  = f.text_field :body, placeholder: 'Your comment'
  = f.collection_radio_buttons :weight, *@form.weights

  = f.fields_for :user do |ff|
    = ff.text_field :email, placeholder: 'Your Email'

  = f.button 'Create Comment'

%h3 #{@thing.comments.size} comments

= concept 'comment/cell/grid', @thing, page: params[:page]

%div
  = link_to 'New', new_thing_path
  = link_to 'Index', things_path